- name: Install vSphere Python SDK used by Ansible to talk to vSphere
  pip:
   name: ['pyvmomi', 'simple-http-server']
  become: True

- name: Ensure required directories exist
  file:
    path: '{{ item }}'
    state: directory
  with_items:
    - '{{ helper.images_dir }}'

- name: Download Red Hat CoreOS OVA template {{ coreos.vmware_ova_url }}
  get_url:
    url: '{{ coreos.vmware_ova_url }}'
    dest: '{{ helper.images_dir }}/{{ coreos.vmware_ova_url | basename }}'
    checksum: 'sha256:{{ coreos.sha256sum_url }}'

- name: webserver
  shell: cd "{{ helper.install_conf_dir }}"; nohup python -m SimpleHTTPServer {{ openshift_install_config.ignition_url_prefix.split(':')[2] }} </dev/null >/dev/null 2>&1 &
